//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_DoAn_LTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public Sach()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<int> MaTacGia { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
