//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_DoAn_LTW
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanChuyen
    {
        public int MaVC { get; set; }
        public Nullable<int> MaDon { get; set; }
        public string TrangThaiVC { get; set; }
        public string QuangDuong { get; set; }
        public string ThoiGianDuKien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
